### ISSUE TITLE
mimetype for sending a message to a phone number

### ISSUE THREAD

**Issue by FPSUsername** [frealgagu/archlinux.whatsapp-nativefier#18]
I was trying to send a message to a phone number that I haven't saved in my address book by using the web API that has the following URL:
https://api.whatsapp.com/send/?phone=THE_PHONE_NUMBER&text&app_absent=0

![image](https://user-images.githubusercontent.com/10143926/158645268-3a0fff3a-e10d-40d1-aa54-ee72a73e6845.png)

Upon clicking the "continue to chat" button, an xdg-open popup opened with the following action:
`whatsapp://send/?phone=THE_PHONE_NUMBER&text&app_absent=0`

I tried modifying `whatsapp-nativefier.desktop` with the following:
```ini
Exec=whatsapp-nativefier %U
MimeType=x-scheme-handler/whatsapp
```

When I clicked the "continue to chat" button, whatsapp-nativefier would open endless processes, forcing me to reboot my machine.
I'm not sure what I'm doing wrong or maybe it's an issue with the program.

**Comment by frealgagu** [comment]
If I click a URL like https://api.whatsapp.com/send/?phone=THE_PHONE_NUMBER&text&app_absent=0 in a chat, it will open the correct chat number, however if I cliked outside the application (adding the corresponging MimeType via 
`xdg-mime default /usr/share/applications/whatsapp-nativefier.desktop x-scheme-handler/whatsapp`
) it start the application but the URL does not load (only opens/focus but not point to the chat).

Using the protocol directly and invoking 
`whatsapp-nativefier "whatsapp://send/?phone=THE_PHONE_NUMBER&text&app_absent=0`
behaves as before (clicking externally).

Finally if I open the app using `whatsapp-nativefier "https://api.whatsapp.com/send/?phone=THE_PHONE_NUMBER&text=something&app_absent=0` it will fail by

```
$ whatsapp-nativefier "https://api.whatsapp.com/send/?phone=THE_PHONE_NUMBER&text=something&app_absent=0"
onReady ERROR Error: ERR_ABORTED (-3) loading 'whatsapp://send/?phone=THE_PHONE_NUMBER&text=something&app_absent=0'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.navigationListener (node:electron/js2c/browser_init:161:7953)
    at EventEmitter.emit (node:events:526:28) {
  errno: -3,
  code: 'ERR_ABORTED',
  url: 'whatsapp://send/?phone=THE_PHONE_NUMBER&text=something&app_absent=0'
}
```
because nativefier is only allowing certain protocols. Same if I click in "Continue to chat"
![image](https://user-images.githubusercontent.com/7220181/204115024-2f94cfcc-563a-4281-8871-b09538663fc5.png)

**Comment by frealgagu** [comment]
And.. finally, if an instance of whatsapp is already running, open a link that redirect will try to open a second one, which cause to close because --single-instance is in configuration. So, I don't think is possible to achieve what you want unfortunately.
