### ISSUE TITLE
Show notification count on tray icon

### ISSUE THREAD

**Issue by bordam** [frealgagu/archlinux.whatsapp-nativefier#27]
Show if and how many whatsapp notifications you have directly in the tray icon

**Comment by frealgagu** [comment]
This package actually is a wrapper of WhatsApp web https://web.whatsapp.com/ using electron so no additional features can be implemented.

**Comment by bordam** [comment]
This is a feature that is possible to implement, [zapzap](https://github.com/rafatosta/zapzap) and other clients do this

**Comment by frealgagu** [comment]
Yes, you are right, what I mean is that whatsapp-nativefier uses nativefier to create the app, so any change should be there to allow that kind of things.

ZapZap and teams-for-linux for example uses electron and have their own customizations, even, a whatsapp-desktop app was created but was removed due to copyright issues.

**Comment by bordam** [comment]
Ohh I see, it's ok then.
